using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace CustomKeyboard
{
    public static class KeyHelper
    {
        [DllImport("user32.dll", EntryPoint = "keybd_event")]
        public static extern void keybd_event(
        byte bVk, //虚拟键值  
        byte bScan,// 一般为0  
        int dwFlags, //这里是整数类型 0 为按下，2为释放  
        int dwExtraInfo //这里是整数类型 一般情况下设成为0  
        );

        public static void OnKeyPress(byte keyCode)
        {
            keybd_event(keyCode, 0, 0, 0);
            keybd_event(keyCode, 0, 2, 0);
        }

        public static void OnKeyDown(byte keyCode)
        {
            keybd_event(keyCode, 0, 0, 0);
        }

        public static void OnKeyUp(byte keyCode)
        {
            keybd_event(keyCode, 0, 2, 0);
        }


    }
    /// <summary>
    /// 虚拟键代码--参考 https://learn.microsoft.com/zh-CN/windows/win32/inputdev/virtual-key-codes
    /// </summary>
    public static class VirtualKeyCodes
    {


        //VK_LBUTTON    =>  The left mouse button
        //VK_RBUTTON    =>  The right mouse button
        //VK_CANCEL    =>  The Cancel virtual key, used for control-break processing
        //VK_MBUTTON    =>  The middle mouse button
        //VK_BACK    =>  Backspace
        //VK_TAB    =>  Tab
        //VK_CLEAR    =>  5(keypad without Num Lock)
        //VK_RETURN    =>  Enter
        //VK_SHIFT    =>  Shift(either one)
        //VK_CONTROL    =>  Ctrl(either one)
        //VK_MENU    =>  Alt(either one)
        //VK_PAUSE    =>  Pause
        //VK_CAPITAL    =>  Caps Lock
        //VK_ESCAPE    =>  Esc
        //VK_SPACE    =>  Spacebar
        //VK_PRIOR    =>  Page Up
        //VK_NEXT    =>  Page Down
        //VK_END    =>  End
        //VK_HOME    =>  Home
        //VK_LEFT    =>  Left Arrow
        //VK_UP    =>  Up Arrow
        //VK_RIGHT    =>  Right Arrow
        //VK_DOWN    =>  Down Arrow
        //VK_SELECT    =>  Select
        //VK_PRINT    =>  Print(only used by Nokia keyboards)
        //VK_EXECUTE    =>  Execute(not used)
        //VK_SNAPSHOT    =>  Print Screen
        //VK_INSERT    =>  Insert
        //VK_DELETE    =>  Delete
        //VK_HELP    =>  Help
        //VK_0    =>  0
        //VK_1    =>  1
        //VK_2    =>  2
        //VK_3    =>  3
        //VK_4    =>  4
        //VK_5    =>  5
        //VK_6    =>  6
        //VK_7    =>  7
        //VK_8    =>  8
        //VK_9    =>  9
        //VK_A    =>  A
        //VK_B    =>  B
        //VK_C    =>  C
        //VK_D    =>  D
        //VK_E    =>  E
        //VK_F    =>  F
        //VK_G    =>  G
        //VK_H    =>  H
        //VK_I    =>  I
        //VK_J    =>  J
        //VK_K    =>  K
        //VK_L    =>  L
        //VK_M    =>  M
        //VK_N    =>  N
        //VK_O    =>  O
        //VK_P    =>  P
        //VK_Q    =>  Q
        //VK_R    =>  R
        //VK_S    =>  S
        //VK_T    =>  T
        //VK_U    =>  U
        //VK_V    =>  V
        //VK_W    =>  W
        //VK_X    =>  X
        //VK_Y    =>  Y
        //VK_Z    =>  Z
        //VK_STARTKEY    =>  Start Menu key
        //VK_CONTEXTKEY    =>  Context Menu key
        //VK_NUMPAD0    =>  0 (keypad with Num Lock)
        //VK_NUMPAD1    =>  1 (keypad with Num Lock)
        //VK_NUMPAD2    =>  2 (keypad with Num Lock)
        //VK_NUMPAD3    =>  3 (keypad with Num Lock)
        //VK_NUMPAD4    =>  4 (keypad with Num Lock)
        //VK_NUMPAD5    =>  5 (keypad with Num Lock)
        //VK_NUMPAD6    =>  6 (keypad with Num Lock)
        //VK_NUMPAD7    =>  7 (keypad with Num Lock)
        //VK_NUMPAD8    =>  8 (keypad with Num Lock)
        //VK_NUMPAD9    =>  9 (keypad with Num Lock)
        //VK_MULTIPLY    =>  * (keypad)
        //VK_ADD    =>  + (keypad)
        //VK_SEPARATER    =>  Separator(never generated by the keyboard)
        //VK_DECIMAL    =>  . (keypad with Num Lock)
        //VK_DIVIDE    =>  / (keypad)
        //VK_F1    =>  F1
        //VK_F2    =>  F2
        //VK_F3    =>  F3
        //VK_F4    =>  F4
        //VK_F5    =>  F5
        //VK_F6    =>  F6
        //VK_F7    =>  F7
        //VK_F8    =>  F8
        //VK_F9    =>  F9
        //VK_F10    =>  F10
        //VK_F11    =>  F11
        //VK_F12    =>  F12   
        //VK_F13    =>  F13   
        //VK_F14    =>  F14    
        //VK_F15    =>  F15      
        //VK_F16    =>  F16     
        //VK_F17    =>  F17       
        //VK_F18    =>  F18      
        //VK_F19    =>  F19       
        //VK_F20    =>  F20      
        //VK_F21    =>  F21
        //VK_F22    =>  F22
        //VK_F23    =>  F23
        //VK_F24    =>  F24
        //VK_NUMLOCK    =>  Num Lock
        //VK_OEM_SCROLL    =>  Scroll Lock
        //VK_OEM_1    =>  ;
        //VK_OEM_PLUS    =>  =
        //VK_OEM_COMMA    =>  ,
        //VK_OEM_MINUS    =>  -
        //VK_OEM_PERIOD    =>  .
        //VK_OEM_2    =>  /
        //VK_OEM_3    =>  `
        //VK_OEM_4    =>  [
        //VK_OEM_5    =>  \
        //VK_OEM_6    =>  ]
        //VK_OEM_7    =>  '
        //VK_OEM_8    =>  (unknown)
        //VK_ICO_F17    =>  F17 on Olivetti extended keyboard(internal use only)
        //VK_ICO_F18    =>  F18 on Olivetti extended keyboard(internal use only)
        //VK_OEM_102<or | on IBM-compatible 102 enhanced non-U.S.keyboard
        //VK_ICO_HELP    =>  Help on Olivetti extended keyboard (internal use only)
        //VK_ICO_00    =>  00 on Olivetti extended keyboard(internal use only)
        //VK_ICO_CLEAR    =>  Clear on Olivette extended keyboard(internal use only)
        //VK_OEM_RESET    =>  Reset(Nokia keyboards only)
        //VK_OEM_JUMP    =>  Jump(Nokia keyboards only)
        //VK_OEM_PA1    =>  PA1(Nokia keyboards only)
        //VK_OEM_PA2    =>  PA2(Nokia keyboards only)
        //VK_OEM_PA3    =>  PA3(Nokia keyboards only)
        //VK_OEM_WSCTRL    =>  WSCTRL(Nokia keyboards only)
        //VK_OEM_CUSEL    =>  CUSEL(Nokia keyboards only)
        //VK_OEM_ATTN    =>  ATTN(Nokia keyboards only)
        //VK_OEM_FINNISH    =>  FINNISH(Nokia keyboards only)
        //VK_OEM_COPY    =>  COPY(Nokia keyboards only)
        //VK_OEM_AUTO    =>  AUTO(Nokia keyboards only)
        //VK_OEM_ENLW    =>  ENLW(Nokia keyboards only)
        //VK_OEM_BACKTAB    =>  BACKTAB(Nokia keyboards only)
        //VK_ATTN    =>  ATTN
        //VK_CRSEL    =>  CRSEL
        //VK_EXSEL    =>  EXSEL
        //VK_EREOF    =>  EREOF
        //VK_PLAY    =>  PLAY
        //VK_ZOOM    =>  ZOOM
        //VK_NONAME    =>  NONAME
        //VK_PA1    =>  PA1
        //VK_OEM_CLEAR    =>  CLEAR
        //VK_LWIN   =>  左win键
        //VK_RWIN   =>  右win键
        public const string VK_LBUTTON="1";
        public const string VK_RBUTTON="2";
        public const string VK_CANCEL="3";
        public const string VK_MBUTTON="4";
        public const string VK_BACK="8";
        public const string VK_TAB="9";
        public const string VK_CLEAR="C";
        public const string VK_RETURN="D";
        public const string VK_SHIFT="10";
        public const string VK_CONTROL="11";
        public const string VK_MENU="12";
        public const string VK_PAUSE="13";
        public const string VK_CAPITAL="14";
        public const string VK_ESCAPE="1B";
        public const string VK_SPACE="20";
        public const string VK_PRIOR="21";
        public const string VK_NEXT="22";
        public const string VK_END="23";
        public const string VK_HOME="24";
        public const string VK_LEFT="25";
        public const string VK_UP="26";
        public const string VK_RIGHT="27";
        public const string VK_DOWN="28";
        public const string VK_SELECT="29";
        public const string VK_PRINT="2A";
        public const string VK_EXECUTE="2B";
        public const string VK_SNAPSHOT="2C";
        public const string VK_INSERT="2D";
        public const string VK_DELETE="2E";
        public const string VK_HELP="2F";
        public const string VK_0="30";
        public const string VK_1="31";
        public const string VK_2="32";
        public const string VK_3="33";
        public const string VK_4="34";
        public const string VK_5="35";
        public const string VK_6="36";
        public const string VK_7="37";
        public const string VK_8="38";
        public const string VK_9="39";
        public const string VK_A="41";
        public const string VK_B="42";
        public const string VK_C="43";
        public const string VK_D="44";
        public const string VK_E="45";
        public const string VK_F="46";
        public const string VK_G="47";
        public const string VK_H="48";
        public const string VK_I="49";
        public const string VK_J="4A";
        public const string VK_K="4B";
        public const string VK_L="4C";
        public const string VK_M="4D";
        public const string VK_N="4E";
        public const string VK_O="4F";
        public const string VK_P="50";
        public const string VK_Q="51";
        public const string VK_R="52";
        public const string VK_S="53";
        public const string VK_T="54";
        public const string VK_U="55";
        public const string VK_V="56";
        public const string VK_W="57";
        public const string VK_X="58";
        public const string VK_Y="59";
        public const string VK_Z="5A";
        public const string VK_STARTKEY="5B";
        public const string VK_CONTEXTKEY="5D";
        public const string VK_NUMPAD0="60";
        public const string VK_NUMPAD1="61";
        public const string VK_NUMPAD2="62";
        public const string VK_NUMPAD3="63";
        public const string VK_NUMPAD4="64";
        public const string VK_NUMPAD5="65";
        public const string VK_NUMPAD6="66";
        public const string VK_NUMPAD7="67";
        public const string VK_NUMPAD8="68";
        public const string VK_NUMPAD9="69";
        public const string VK_MULTIPLY="6A";
        public const string VK_ADD="6B";
        public const string VK_SEPARATOR="6C";
        public const string VK_SUBTRACT="6D";
        public const string VK_DECIMAL="6E";
        public const string VK_DIVIDE="6F";
        public const string VK_F1="70";
        public const string VK_F2="71";
        public const string VK_F3="72";
        public const string VK_F4="73";
        public const string VK_F5="74";
        public const string VK_F6="75";
        public const string VK_F7="76";
        public const string VK_F8="77";
        public const string VK_F9="78";
        public const string VK_F10="79";
        public const string VK_F11="7A";
        public const string VK_F12="7B";
        public const string VK_F13="7C";
        public const string VK_F14="7D";
        public const string VK_F15="7E";
        public const string VK_F16="7F";
        public const string VK_F17="80";
        public const string VK_F18="81";
        public const string VK_F19="82";
        public const string VK_F20="83";
        public const string VK_F21="84";
        public const string VK_F22="85";
        public const string VK_F23="86";
        public const string VK_F24="87";
        public const string VK_NUMLOCK="90";
        public const string VK_OEM_SCROLL="91";
        public const string VK_OEM_1="BA";
        public const string VK_OEM_PLUS="BB";
        public const string VK_OEM_COMMA="BC";
        public const string VK_OEM_MINUS="BD";
        public const string VK_OEM_PERIOD="BE";
        public const string VK_OEM_2="BF";
        public const string VK_OEM_3="C0";
        public const string VK_OEM_4="DB";
        public const string VK_OEM_5="DC";
        public const string VK_OEM_6="DD";
        public const string VK_OEM_7="DE";
        public const string VK_OEM_8="DF";
        public const string VK_ICO_F17="E0";
        public const string VK_ICO_F18="E1";
        public const string VK_OEM102="E2";
        public const string VK_ICO_HELP="E3";
        public const string VK_ICO_00="E4";
        public const string VK_ICO_CLEAR="E6";
        public const string VK_OEM_RESET="E9";
        public const string VK_OEM_JUMP="EA";
        public const string VK_OEM_PA1="EB";
        public const string VK_OEM_PA2="EC";
        public const string VK_OEM_PA3="ED";
        public const string VK_OEM_WSCTRL="EE";
        public const string VK_OEM_CUSEL="EF";
        public const string VK_OEM_ATTN="F0";
        public const string VK_OEM_FINNISH="F1";
        public const string VK_OEM_COPY="F2";
        public const string VK_OEM_AUTO="F3";
        public const string VK_OEM_ENLW="F4";
        public const string VK_OEM_BACKTAB="F5";
        public const string VK_ATTN="F6";
        public const string VK_CRSEL="F7";
        public const string VK_EXSEL="F8";
        public const string VK_EREOF="F9";
        public const string VK_PLAY="FA";
        public const string VK_ZOOM="FB";
        public const string VK_NONAME="FC";
        public const string VK_PA1="FD";
        public const string VK_OEM_CLEAR="FE";
        public const string VK_LWIN = "5B";
        public const string VK_RWIN = "5C";
        
    }
}
